version: "3"

services:
  db:
    platform: "linux/amd64"
    image: mysql:5.7
    ports:
      - "3306:3306"
    volumes:
      - ./db_data:/var/lib/mysql:delegated
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: somewordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress

  wordpress:
    depends_on:
      - db
    image: wordpress:php7.4-apache
    ports:
      - "80:80"
    volumes:
      - ./src:/var/www/html:delegated
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
